version: '3'
services:
  db:
    image: mongo:3.0.2

  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - 5001:80  # host:container
    links:
      - db
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
      - website

  website:
    build: ./website
    command: python -u flask_brevets.py
    volumes:
      - ./website:/web
    ports:
      - 5000:5000  # host:container
    links:
      - db
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
